# Generated by Django 6.0.5 on 2026-08-03 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.PositiveSmallIntegerField()),
                ('d', models.PositiveSmallIntegerField()),
                ('q', models.PositiveSmallIntegerField()),
                ('seasonal_p', models.PositiveSmallIntegerField()),
                ('seasonal_d', models.PositiveSmallIntegerField()),
                ('seasonal_q', models.PositiveSmallIntegerField()),
                ('seasonal_period', models.PositiveSmallIntegerField()),
                ('aic', models.FloatField(blank=True, null=True)),
                ('bic', models.FloatField(blank=True, null=True)),
                ('forecast_horizon', models.PositiveIntegerField(default=30)),
                ('execution_time_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='datasets.dataset')),
                ('processing_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='processing.processingjob')),
                ('stationary_dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecasts', to='processing.datasetversion')),
            ],
            options={
                'verbose_name': 'Forecast',
                'verbose_name_plural': 'Forecasts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(db_index=True)),
                ('predicted_value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('lower_confidence', models.DecimalField(decimal_places=4, max_digits=14)),
                ('upper_confidence', models.DecimalField(decimal_places=4, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='forecasting.forecast')),
            ],
            options={
                'verbose_name': 'Forecast Value',
                'verbose_name_plural': 'Forecast Values',
                'ordering': ['forecast', 'forecast_date'],
            },
        ),
        migrations.AddIndex(
            model_name='forecast',
            index=models.Index(fields=['dataset', 'created_at'], name='forecast_dataset_idx'),
        ),
        migrations.AddIndex(
            model_name='forecast',
            index=models.Index(fields=['processing_job'], name='forecast_job_idx'),
        ),
        migrations.AddIndex(
            model_name='forecast',
            index=models.Index(fields=['created_at'], name='forecast_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='forecast',
            constraint=models.CheckConstraint(condition=models.Q(('forecast_horizon__gte', 1)), name='forecast_horizon_positive'),
        ),
        migrations.AddConstraint(
            model_name='forecast',
            constraint=models.CheckConstraint(condition=models.Q(('seasonal_period__gte', 1)), name='seasonal_period_positive'),
        ),
        migrations.AddIndex(
            model_name='forecastvalue',
            index=models.Index(fields=['forecast', 'forecast_date'], name='value_forecast_date_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastvalue',
            index=models.Index(fields=['forecast_date'], name='value_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='forecastvalue',
            constraint=models.UniqueConstraint(fields=('forecast', 'forecast_date'), name='uniq_value_per_forecast_date'),
        ),
        migrations.AddConstraint(
            model_name='forecastvalue',
            constraint=models.CheckConstraint(condition=models.Q(('upper_confidence__gte', models.F('lower_confidence'))), name='value_upper_gte_lower'),
        ),
        migrations.AddConstraint(
            model_name='forecastvalue',
            constraint=models.CheckConstraint(condition=models.Q(('predicted_value__gte', 0)), name='value_non_negative'),
        ),
    ]
