# Generated by Django 6.0.5 on 2026-06-07 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreprocessDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('CLEANING', 'Cleaning'), ('OUTLIER', 'Outlier'), ('STATIONARITY', 'Stationarity')], max_length=20)),
                ('file_path', models.TextField(help_text='Path to the generated dataset for this stage.')),
                ('instructions', models.JSONField(blank=True, default=dict, help_text='User-selected preprocessing instructions.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Stage results, statistics, logs, and summaries.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(help_text='Original uploaded dataset.', on_delete=django.db.models.deletion.CASCADE, related_name='preprocessing_stages', to='datasets.dataset')),
                ('predecessor', models.ForeignKey(blank=True, help_text='Previous preprocessing stage.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='successors', to='preprocess.preprocessdataset')),
            ],
            options={
                'db_table': 'preprocess_dataset',
                'ordering': ['created_at'],
            },
        ),
    ]
