# Generated by Django 6.0.5 on 2026-06-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='company',
        ),
        migrations.RemoveField(
            model_name='account',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='account',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
