"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-m!hwex@i)8432#lt+5ae=rm&fj5&ji*4$j7r!hwys_1a#oi8n9"

#
#
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
}
#
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    # Free up the `format` query param for our report export
    # (?format=pdf|csv). DRF otherwise reserves it for content
    # negotiation and 404s on unknown formats.
    "URL_FORMAT_OVERRIDE": None,
}
#

# SECURITY WARNING: don't run with debug turned on in production!
# Off by default; set DEBUG=true in the local env for development.
DEBUG = os.environ.get("DEBUG", "false").lower() in ("1", "true", "yes", "on")

# Comma-separated in the env; Render's hostname is injected automatically.
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if h.strip()
]
_render_host = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if _render_host:
    ALLOWED_HOSTS.append(_render_host)

# The deployed frontend origin(s), comma-separated, plus the dev servers.
_frontend_origins = [
    o.strip()
    for o in os.environ.get("FRONTEND_ORIGINS", "").split(",")
    if o.strip()
]
CORS_ALLOWED_ORIGINS = _frontend_origins + [
    "http://localhost:5173",
    "http://localhost:5174",
    "http://localhost:5175",
]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = _frontend_origins + [
    "http://localhost:5173",
    "http://localhost:5174",
    "http://localhost:5175",
]
if _render_host:
    CSRF_TRUSTED_ORIGINS.append(f"https://{_render_host}")

# CORS_ALLOW_HEADERS = list(default_headers)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # APPS
    "apps.accounts.apps.AccountsConfig",
    "apps.core.apps.CoreConfig",
    "apps.datasets.apps.DatasetsConfig",
    "apps.processing.apps.ProcessingConfig",
    "apps.forecasting.apps.ForecastingConfig",
    "apps.evaluation.apps.EvaluationConfig",
    "apps.dashboard.apps.DashboardConfig",
    "apps.reports.apps.ReportsConfig",
    "apps.preprocess.apps.PreprocessConfig",
    #
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    #     "apps.notifications.apps.NotificationsConfig",
    #     "apps.audit.apps.AuditConfig",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    #
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    #
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Accept both DB_* and ENERGY_DB_* env names; fall back to local dev defaults.
def _db_env(key, default):
    return os.environ.get(f"DB_{key}") or os.environ.get(f"ENERGY_DB_{key}", default)


DATABASES = {
    "default": {
        "ENGINE": _db_env("ENGINE", "django.db.backends.mysql"),
        "NAME": _db_env("NAME", "energy_forecast"),
        "USER": _db_env("USER", "root"),
        "PASSWORD": _db_env("PASSWORD", "12345678"),
        "HOST": _db_env("HOST", "127.0.0.1"),
        "PORT": _db_env("PORT", "3306"),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
    }
}


# Custom email-authenticated user model.
AUTH_USER_MODEL = "accounts.User"


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise serves collected static files in production (DEBUG=False).
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"
    },
}

# Media files (uploaded datasets, exported reports).
# MEDIA_ROOT is BASE_DIR so the existing datasets/ and reports/
# storage paths resolve consistently; only the reports/ subtree
# is web-served (see config/urls.py), never the project root.
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR
