# Generated by Django 6.0.5 on 2026-08-03 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('stage', models.CharField(choices=[('raw', 'Raw'), ('cleaned', 'Cleaned'), ('outliers', 'Outliers'), ('stationary', 'Stationary'), ('forecast', 'Forecast')], db_index=True, max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='datasets.dataset')),
            ],
            options={
                'verbose_name': 'Dataset Version',
                'verbose_name_plural': 'Dataset Versions',
                'ordering': ['processing_job', 'version_number'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255)),
                ('current_stage', models.CharField(choices=[('raw', 'Raw'), ('cleaned', 'Cleaned'), ('outliers', 'Outliers'), ('stationary', 'Stationary'), ('forecast', 'Forecast')], db_index=True, default='raw', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='datasets.dataset')),
            ],
            options={
                'verbose_name': 'Processing Job',
                'verbose_name_plural': 'Processing Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreprocessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('raw', 'Raw'), ('cleaned', 'Cleaned'), ('outliers', 'Outliers'), ('stationary', 'Stationary'), ('forecast', 'Forecast')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='success', max_length=20)),
                ('processing_time_ms', models.PositiveIntegerField(default=0)),
                ('missing_values_fixed', models.PositiveIntegerField(default=0)),
                ('duplicate_rows_removed', models.PositiveIntegerField(default=0)),
                ('invalid_rows_removed', models.PositiveIntegerField(default=0)),
                ('outliers_detected', models.PositiveIntegerField(default=0)),
                ('outliers_imputed', models.PositiveIntegerField(default=0)),
                ('iqr_lower', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('iqr_upper', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('adf_statistic', models.FloatField(blank=True, null=True)),
                ('p_value', models.FloatField(blank=True, null=True)),
                ('differencing_order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preprocessing_logs', to='processing.datasetversion')),
                ('processing_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preprocessing_logs', to='processing.processingjob')),
            ],
            options={
                'verbose_name': 'Preprocessing Log',
                'verbose_name_plural': 'Preprocessing Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='datasetversion',
            name='processing_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='processing.processingjob'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['dataset', 'status'], name='job_dataset_status_idx'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['status', 'current_stage'], name='job_status_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['created_at'], name='job_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='processingjob',
            constraint=models.CheckConstraint(condition=models.Q(('started_at__isnull', True), ('completed_at__isnull', True), ('completed_at__gte', models.F('started_at')), _connector='OR'), name='job_completed_after_started'),
        ),
        migrations.AddIndex(
            model_name='preprocessinglog',
            index=models.Index(fields=['processing_job', 'stage'], name='log_job_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='preprocessinglog',
            index=models.Index(fields=['status'], name='log_status_idx'),
        ),
        migrations.AddIndex(
            model_name='preprocessinglog',
            index=models.Index(fields=['created_at'], name='log_created_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetversion',
            index=models.Index(fields=['dataset', 'stage'], name='version_dataset_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetversion',
            index=models.Index(fields=['created_at'], name='version_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='datasetversion',
            constraint=models.UniqueConstraint(fields=('processing_job', 'version_number'), name='uniq_version_per_job'),
        ),
        migrations.AddConstraint(
            model_name='datasetversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gte', 1)), name='version_number_positive'),
        ),
    ]
