# Generated by Django 6.0.5 on 2026-08-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='progress_done',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='progress_phase',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='progress_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
