# Generated by Django 6.0.5 on 2026-08-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_processingjob_progress_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='progress_best',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='progress_best_aic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='progress_candidate',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
